INSERT INTO SEGURIDAD.PERFIL
(NOMBREPERFIL, BDUSRPERFIL, BDPWDPERFIL, PERFILPUBLICO)
VALUES('Invitado', 'siportadm', SEGURIDAD.SF_ENCRYPT('Analista$1'), 'S')
;

GOTO

INSERT INTO SEGURIDAD.PERFIL
(NOMBREPERFIL, BDUSRPERFIL, BDPWDPERFIL, PERFILPUBLICO)
VALUES('Adminsitrador', 'siportadm', SEGURIDAD.SF_ENCRYPT('Analista$1'), 'N');
