
CREATE TABLE OPERACIONES.PLANHOJADERUTACAB
(
	IDPLANHOJADERUTACAB		BIGINT NOT NULL PRIMARY KEY,
	CODIGOPLANIFICACION		CHAR(6) NOT NULL,
	COMENTARIOPLANIFICACION	VARCHAR(200)
)
GO
CREATE TABLE OPERACIONES.PLANHOJADERUTADET
(
	IDPLANHOJADERUTADET		BIGINT NOT NULL PRIMARY KEY,
	IDPLANHOJADERUTACAB  	BIGINT NOT NULL FOREIGN KEY REFERENCES OPERACIONES.PLANHOJADERUTACAB(IDPLANHOJADERUTACAB),
	IDVEHICULO				BIGINT NOT NULL FOREIGN KEY REFERENCES OPERACIONES.VEHICULO(IDVEHICULO), 
	IDORDENSERVICIO			BIGINT NOT NULL,
	IDORDENSERVICIODESTINO	BIGINT NOT NULL FOREIGN KEY REFERENCES OPERACIONES.ORDENSERVICIODESTINO(IDORDENSERVICIODESTINO), 
	ORDENATENCION			INT,
	FECHACREACION			DATE,
	USUARIOCREACION			VARCHAR(20)
)

