CREATE DATABASE SIPORTBD;

GO

USE SIPORTBD

GO


CREATE LOGIN siportadm WITH PASSWORD = 'Analista$1';
USE SIPORTBD;
CREATE USER siportadm FOR LOGIN siportadm;

GO

CREATE SCHEMA SEGURIDAD AUTHORIZATION siportadm;

GO




GRANT SELECT ON SCHEMA::SEGURIDAD TO siportadm;

GO

CREATE TABLE SEGURIDAD.USUARIO(
	IDUSUARIO bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CODIGOUSUARIO varchar(20) NULL,
	NOMBREUSUARIO varchar(150) NULL,
	ESTADOUSUARIO char(1) NULL,
	EMAILUSUARIO varchar(150) NULL,
	FECHAREGISTRO datetime NULL,
	ISAPPROVED smallint NULL,
	ISLOCKEDOUT smallint NULL,
	ISONLINE smallint NULL,
	LASTACTIVITYDATE smalldatetime NULL,
	LASTLOCKEDOUTDATE smalldatetime NULL,
	LASTLOGINDATE smalldatetime NULL,
); 

GO


CREATE TABLE SEGURIDAD.USUARIOPWD(
	IDUSUARIOPWD bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IDUSUARIO bigint NOT NULL,
	PASSWORD varbinary(2000) NOT NULL,
	RECORDATORIOPWD varchar(30) NULL,
	FECHAVCTOPWD datetime NULL,
	FECHAMODIFICACION datetime NULL,
	PUEDECAMBIARPWD smallint NULL,
) 
GO

ALTER TABLE SEGURIDAD.USUARIOPWD  
	WITH CHECK ADD  CONSTRAINT FK_USUARIOPWD_USUARIO FOREIGN KEY(IDUSUARIO)
REFERENCES SEGURIDAD.USUARIO (IDUSUARIO)
ON DELETE CASCADE
GO

ALTER TABLE SEGURIDAD.USUARIOPWD CHECK CONSTRAINT FK_USUARIOPWD_USUARIO
GO


CREATE TABLE SEGURIDAD.PERFIL(
	IDPERFIL bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBREPERFIL varchar(50) NOT NULL,
	BDUSRPERFIL varchar(30) NULL,
	BDPWDPERFIL varbinary(2000) NULL,
	PERFILPUBLICO char(1) NULL
)

GO

CREATE TABLE SEGURIDAD.MENU(
	IDMENU bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IDMENUPADRE bigint NULL,
	NIVEL int NULL,
	NOMBRE varchar(30) NULL,
	DESCRIPCION varchar(100) NULL,
	URL varchar(150) NULL,
	TIPO char(1) NULL
) 


GO



CREATE TABLE SEGURIDAD.MENUPERFIL(
	IDMENUPERFIL bigint IDENTITY(1,1) PRIMARY KEY  NOT NULL,
	IDMENU bigint NOT NULL,
	IDPERFIL bigint NOT NULL
)
GO

ALTER TABLE SEGURIDAD.MENUPERFIL  
	WITH CHECK ADD  CONSTRAINT FK_MENU_PERFIL_IDMENU FOREIGN KEY(IDMENU)
REFERENCES SEGURIDAD.MENU (IDMENU)
ON DELETE CASCADE

GO

ALTER TABLE SEGURIDAD.MENUPERFIL  
	WITH CHECK ADD  CONSTRAINT FK_MENU_PERFIL_IDPERFIL FOREIGN KEY(IDPERFIL)
REFERENCES SEGURIDAD.PERFIL (IDPERFIL)
ON DELETE CASCADE

GO


CREATE TABLE SEGURIDAD.USUARIOPERFIL(
	IDUSUARIOPERFIL bigint IDENTITY(1,1) PRIMARY KEY NOT NULL,
	IDUSUARIO bigint NOT NULL,
	IDPERFIL bigint NOT NULL
)
GO

ALTER TABLE SEGURIDAD.USUARIOPERFIL  WITH CHECK ADD  CONSTRAINT FK_USUARIOPERFIL_PERFIL FOREIGN KEY(IDPERFIL)
REFERENCES SEGURIDAD.PERFIL (IDPERFIL)
ON DELETE CASCADE
GO

ALTER TABLE SEGURIDAD.USUARIOPERFIL CHECK CONSTRAINT FK_USUARIOPERFIL_PERFIL
GO

ALTER TABLE SEGURIDAD.USUARIOPERFIL  WITH CHECK ADD  CONSTRAINT FK_USUARIOPERFIL_USUARIO FOREIGN KEY(IDUSUARIO)
REFERENCES SEGURIDAD.USUARIO (IDUSUARIO)
ON DELETE CASCADE
GO

ALTER TABLE SEGURIDAD.USUARIOPERFIL CHECK CONSTRAINT FK_USUARIOPERFIL_USUARIO
GO


GO

